// NOTE: this server is purely a dev-mode server. In production, the
// server/index.js server also serves the API routes.

// Configure process.env with .env.* files
require('./env').configureEnv();

const express = require('express');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const cors = require('cors');
const apiRouter = require('./apiRouter');
const wellKnownRouter = require('./wellKnownRouter');
const webmanifestResourceRoute = require('./resources/webmanifest');
const robotsTxtRoute = require('./resources/robotsTxt');
const sitemapResourceRoute = require('./resources/sitemap');

const radix = 10;
const PORT = parseInt(process.env.REACT_APP_DEV_API_SERVER_PORT, radix);
const app = express();

// NOTE: CORS is only needed in this dev API server because it's
// running in a different port than the main app.
// XOLOLO: aceptamos también wildcards *.localhost:3000 y *.xololo.mx para
// que las storefronts en subdominio puedan pegarle a /api en dev.
const rootUrl = process.env.REACT_APP_MARKETPLACE_ROOT_URL;
const isXololoOrigin = origin => {
  if (!origin) return true; // same-origin/curl
  if (origin === rootUrl) return true;
  try {
    const { hostname, port } = new URL(origin);
    if (hostname === 'localhost' || hostname.endsWith('.localhost')) {
      return port === '3000';
    }
    if (hostname === 'xololo.mx' || hostname.endsWith('.xololo.mx')) return true;
  } catch {}
  return false;
};
app.use(
  cors({
    origin: (origin, cb) => cb(null, isXololoOrigin(origin)),
    credentials: true,
  })
);
app.use(cookieParser());
app.use('/.well-known', wellKnownRouter);
app.use('/api', apiRouter);

// Generate web app manifest
// When developing with "yarn run dev",
// you can reach the manifest from http://localhost:3500/site.webmanifest
// The corresponding <link> element is set in src/components/Page/Page.js
app.get('/site.webmanifest', webmanifestResourceRoute);

// robots.txt and sitemap-* fetches should return similarly compressed data as server/index.js
app.use(compression());

// robots.txt is generated by resources/robotsTxt.js
// It creates the sitemap URL with the correct marketplace URL
app.get('/robots.txt', robotsTxtRoute);

// Handle different sitemap-* resources. E.g. /sitemap-index.xml
app.get('/sitemap-:resource', sitemapResourceRoute);

app.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`API server listening on ${PORT}`);
});
